import { NextPage } from "next";

const Page: NextPage = () => {
  return (
    <>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
      <div>WIP</div>
    </>
  );
};

export default Page;
